OOP school library: add basic UI
78fatemanazari/OOP-School-Library pull request #4
Opened 2023-10-27 19:55 UTC by 78fatemanazari

### Project Requirements
- Create a `app.rb` file that will serve as your console app entry-point. It should have methods that do the following:
  - List all books.
  - List all people.
  - Create a person (teacher or student, not a plain `Person`).
  - Create a book.
  - Create a rental.
  - List all rentals for a given person id.
- In your `main.rb` define the entry point, this will be a method called `main` that is invoked at the end of your file. This method should do the following:
  - Present the user with a list of options to perform.
  - Lets users choose an option.
  - If needed, ask for parameters for the option.
  - Have a way to quit the app.

2023-10-27 21:02 UTC, Johnadibe requested changes
# STATUS: REQUIRED CHANGES ♻️
### Hi @78fatemanazari👋🏽, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights
✅ You used GitFlow correctly 👍🏽
✅ Linter checks passed✔️
✅ Created an app.rb file that serves as a console app entry point with its methods✔
✅ Defined the entry point in main.rb file, which is invoked at the end of the file✔

## Required Changes ♻️

> - [ ] Please I suggest you add one or two key features of the project to your Readme file. This will help others to understand your project better.👍
>
> ![key](https://github.com/78fatemanazari/OOP-School-Library/assets/40009354/9c1cc5b6-80ef-447b-ad72-7ba558e7be7f)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-27 21:02 UTC, Johnadibe commented on app.rb
> +  end
> - [ ] Hello @78fatemanazari, I noticed that when I try to create a teacher person, I get the following error message below, Please could you address this issue?👍
> 
> ![oo](https://github.com/78fatemanazari/OOP-School-Library/assets/40009354/30faef3a-5722-4e41-8a9d-c0f6f1d7524e)
>

2023-10-27 21:02 UTC, Johnadibe commented on app.rb
> +    end
> - [ ] Good job so far👍, but I'm having trouble finding the ID of the person that was created when I try to list all rentals for a given person ID. Please kindly fix that and see the attached image for more details.👍
> 
> ![oi](https://github.com/78fatemanazari/OOP-School-Library/assets/40009354/0bcb5cbe-e230-4afd-ab87-cffdf12c2214)

2023-10-27 21:02 UTC, Johnadibe commented on app.rb
> +  end
> - [ ] When I list all the people created, they do not have any assigned IDs. This is because the IDs are empty. Please fix this.👍
> 
> ![li](https://github.com/78fatemanazari/OOP-School-Library/assets/40009354/fda04fe6-4fdd-4f2f-92f6-658e11273eb6)
>

2023-10-28 06:20 UTC, Bantealem approved these changes
# Status: Approved
Hi @78fatemanazari , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![Screenshot from 2023-09-27 20-56-29](https://github.com/78fatemanazari/OOP-School-Library/assets/101523582/e8aaf78a-745a-4a9d-a1ef-4675099c4222)

## Highlights
- [x] Professional Readme
- [x] Linters are passed
- [x] Descriptive PR summary
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-28 12:13 UTC, merged